baseURL = "https://michael18811380328.github.io/MyBlog/"
languageCode = "zh-cn"
title = "我的笔记"
contentDir = "docs"
disableKinds = ["taxonomy", "term"]

[params]
  author = "Michael An"
  description = "Michael An 的个人博客"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    noClasses = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    codeFences = true
